"""FAISS + S3-compatible local vector store for RetainAI.

If faiss-cpu and index.faiss are available, retrieval uses FAISS. Otherwise it
uses index.json fallback vectors generated by modules.rag.build_faiss_index.
"""

from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path
import random
from typing import Any

from modules.rag.vector_store import VectorSearchResult, VectorStore

DEFAULT_EMBEDDING_DIMENSION = 128
DEFAULT_EMBEDDING_MODEL = "local-hash-embedding-v1"


def deterministic_embedding(text: str, dimension: int = DEFAULT_EMBEDDING_DIMENSION) -> list[float]:
    """Create a deterministic local embedding for connector smoke tests."""
    seed = int(hashlib.sha256(text.encode("utf-8")).hexdigest()[:16], 16)
    generator = random.Random(seed)
    values = [generator.uniform(-1.0, 1.0) for _ in range(dimension)]
    norm = math.sqrt(sum(value * value for value in values)) or 1.0
    return [value / norm for value in values]


def cosine_similarity(left: list[float], right: list[float]) -> float:
    """Compute cosine similarity for normalized vectors."""
    return float(sum(a * b for a, b in zip(left, right)))


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


class FaissS3VectorStore(VectorStore):
    """Local FAISS/S3 vector-store connector."""

    def __init__(self, index_path: str | Path = "artifacts/rag/vector-index/faiss") -> None:
        self.index_path = Path(index_path)
        self.documents_path = self.index_path / "documents.jsonl"
        self.metadata_path = self.index_path / "metadata.json"
        self.index_json_path = self.index_path / "index.json"
        self.index_faiss_path = self.index_path / "index.faiss"

        if not self.metadata_path.exists():
            raise FileNotFoundError(f"Missing vector index metadata: {self.metadata_path}")

        self.metadata = _read_json(self.metadata_path)
        self.dimension = int(self.metadata.get("embedding_dimension", DEFAULT_EMBEDDING_DIMENSION))
        self.documents_payload = _read_jsonl(self.documents_path)

        self._np = None
        self._faiss_index = None
        self._try_load_faiss()

        self._fallback_vectors = []
        if self._faiss_index is None:
            if not self.index_json_path.exists():
                raise FileNotFoundError(f"Missing fallback vector index: {self.index_json_path}")
            self._fallback_vectors = _read_json(self.index_json_path).get("vectors", [])

    @property
    def backend(self) -> str:
        """Return active retrieval backend."""
        return "faiss" if self._faiss_index is not None else "numpy_fallback"

    def _try_load_faiss(self) -> None:
        if not self.index_faiss_path.exists():
            return
        try:
            import faiss  # type: ignore
            import numpy as np  # type: ignore
        except Exception:
            return

        self._np = np
        self._faiss_index = faiss.read_index(str(self.index_faiss_path))

    def _to_result(self, payload: dict[str, Any], score: float) -> VectorSearchResult:
        text = str(payload.get("text", ""))
        return VectorSearchResult(
            document_id=str(payload.get("document_id", "")),
            title=str(payload.get("title", "")),
            text=text[:1200],
            score=float(score),
            source_path=str(payload.get("source_path", "")),
            metadata=dict(payload.get("metadata", {})),
        )

    def search(self, query: str, top_k: int = 5) -> list[VectorSearchResult]:
        """Retrieve top-k documents locally."""
        if top_k <= 0:
            return []

        query_vector = deterministic_embedding(query, self.dimension)

        if self._faiss_index is not None and self._np is not None:
            query_array = self._np.array([query_vector], dtype="float32")
            scores, indexes = self._faiss_index.search(query_array, top_k)
            results: list[VectorSearchResult] = []
            for score, idx in zip(scores[0].tolist(), indexes[0].tolist()):
                if idx >= 0 and idx < len(self.documents_payload):
                    results.append(self._to_result(self.documents_payload[idx], float(score)))
            return results

        scored = [
            (cosine_similarity(query_vector, [float(value) for value in vector]), idx)
            for idx, vector in enumerate(self._fallback_vectors)
        ]
        scored.sort(reverse=True, key=lambda item: item[0])

        return [
            self._to_result(self.documents_payload[idx], score)
            for score, idx in scored[:top_k]
            if idx < len(self.documents_payload)
        ]
